{
    'name': 'Hason Sales',
    'version': '17.0.1.0.0',
    'summary': 'Add Transport Name field in Sale Order',
    'category': 'Sales',
    'author': 'Applified',
    'depends': ['sale', 'l10n_in', 'stock','sale_stock', 'account','crm'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/sale_order_view.xml',
        'views/product_packaging_view.xml',
        'views/vehicle_master_view.xml',
        # 'reports/report_saleorder_inherit.xml',
        'reports/proforma_invoice.xml',
        'reports/custom_quotation.xml',
            ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}